### ISSUE TITLE
Missing vars added

### ISSUE THREAD

**Issue by drumfreak** [avenger11/Homebridge-Oittm-Humidifier#1]
https://github.com/avenger11/Homebridge-Oittm-Humidifier/blob/7c001cb18ba50f4dfe2a83ad3c2114cf6a439d03/index.js#L2

Someone reported missing vars in their homebridge. Check this out:

[commit 6ef1da6e6](https://github.com/drumfreak/homebridge-tuya-colorlight/commit/4ca8b11d9e0b12aa85b0adf964245166ef1da6e6)

Nice work, I'll keep track of this and add it to the platform coming up!

**Comment by avenger11** [comment]
added
